#!/bin/bash
# =============================================================================
# PiFace Attendance System - Full Installation Script
# Target: Raspberry Pi 5, Raspberry Pi OS Bookworm 64-bit
# Run as root: sudo bash install.sh
# =============================================================================
set -euo pipefail

LOG_FILE="/var/log/piface-install.log"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIFACE_HOME="/opt/piface"
PIFACE_USER="piface"
WLAN_IP="192.168.4.1"

# ---------------------------------------------------------------------------
# Error trap: log failures with line number
# ---------------------------------------------------------------------------
trap 'echo "[$(date +"%Y-%m-%d %H:%M:%S")] ERROR on line $LINENO (exit $?)" | tee -a "$LOG_FILE"' ERR

exec > >(tee -a "$LOG_FILE") 2>&1
echo "=========================================="
echo " PiFace Install  -  $(date)"
echo "=========================================="

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root."
    exit 1
fi

if ! grep -qi "bookworm" /etc/os-release 2>/dev/null; then
    echo "WARNING: This script targets Raspberry Pi OS Bookworm. Proceeding anyway..."
fi

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
echo "[1/20] Updating system packages..."
apt-get update -y
apt-get upgrade -y

echo "[2/20] Installing required packages..."
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    hostapd \
    dnsmasq \
    nginx \
    python3-pip \
    python3-venv \
    python3-dev \
    build-essential \
    cmake \
    libopenblas-dev \
    libcap-dev \
    i2c-tools \
    iptables-persistent

# ---------------------------------------------------------------------------
# 2. NetworkManager: ignore wlan0
# ---------------------------------------------------------------------------
echo "[3/20] Configuring NetworkManager to ignore wlan0..."
mkdir -p /etc/NetworkManager/conf.d
cat > /etc/NetworkManager/conf.d/piface.conf <<'NM_EOF'
[keyfile]
unmanaged-devices=interface-name:wlan0
NM_EOF

systemctl restart NetworkManager || true

# ---------------------------------------------------------------------------
# 3. Disable systemd-resolved, fix resolv.conf
# ---------------------------------------------------------------------------
echo "[4/20] Disabling systemd-resolved..."
systemctl disable --now systemd-resolved 2>/dev/null || true

rm -f /etc/resolv.conf
cat > /etc/resolv.conf <<'RESOLV_EOF'
# Generated by PiFace install script
nameserver 8.8.8.8
nameserver 1.1.1.1
RESOLV_EOF

# ---------------------------------------------------------------------------
# 4. Static IP for wlan0 via systemd-networkd
# ---------------------------------------------------------------------------
echo "[5/20] Configuring static IP for wlan0..."
cp "${SCRIPT_DIR}/10-wlan0.network" /etc/systemd/network/10-wlan0.network
chmod 644 /etc/systemd/network/10-wlan0.network

systemctl enable systemd-networkd
systemctl restart systemd-networkd || true

# ---------------------------------------------------------------------------
# 5. hostapd & dnsmasq
# ---------------------------------------------------------------------------
echo "[6/20] Installing hostapd and dnsmasq configs..."
cp "${SCRIPT_DIR}/hostapd.conf" /etc/hostapd/hostapd.conf
chmod 600 /etc/hostapd/hostapd.conf

cp "${SCRIPT_DIR}/dnsmasq.conf" /etc/dnsmasq.conf
chmod 644 /etc/dnsmasq.conf

# Point hostapd daemon config to the right file
sed -i 's|^#\?DAEMON_CONF=.*|DAEMON_CONF="/etc/hostapd/hostapd.conf"|' /etc/default/hostapd 2>/dev/null || true

systemctl unmask hostapd 2>/dev/null || true
systemctl enable hostapd
systemctl enable dnsmasq

# ---------------------------------------------------------------------------
# 6. Create piface system user
# ---------------------------------------------------------------------------
echo "[7/20] Creating piface system user..."
if ! id "$PIFACE_USER" &>/dev/null; then
    useradd -r -s /usr/sbin/nologin -d "$PIFACE_HOME" "$PIFACE_USER"
fi

# Add to supplementary groups (create groups if missing)
for grp in gpio video i2c; do
    getent group "$grp" &>/dev/null || groupadd -r "$grp"
    usermod -aG "$grp" "$PIFACE_USER"
done

# ---------------------------------------------------------------------------
# 7. Directory structure
# ---------------------------------------------------------------------------
echo "[8/20] Creating directory structure under ${PIFACE_HOME}..."
mkdir -p \
    "${PIFACE_HOME}/database" \
    "${PIFACE_HOME}/snapshots" \
    "${PIFACE_HOME}/reports" \
    "${PIFACE_HOME}/backups" \
    "${PIFACE_HOME}/models" \
    "${PIFACE_HOME}/certs" \
    "${PIFACE_HOME}/config" \
    "${PIFACE_HOME}/helpers" \
    "${PIFACE_HOME}/core" \
    "${PIFACE_HOME}/backend/routes" \
    "${PIFACE_HOME}/frontend"

mkdir -p /var/log/piface
mkdir -p /run/piface

chown -R "${PIFACE_USER}:${PIFACE_USER}" "${PIFACE_HOME}" /var/log/piface /run/piface

# ---------------------------------------------------------------------------
# 7b. Copy application code
# ---------------------------------------------------------------------------
echo "[8b/20] Copying application code to ${PIFACE_HOME}..."
APP_SRC="$(cd "${SCRIPT_DIR}/.." && pwd)"
cp -r "${APP_SRC}/backend/"* "${PIFACE_HOME}/backend/"
cp -r "${APP_SRC}/core/"*    "${PIFACE_HOME}/core/"
cp "${APP_SRC}/__init__.py"  "${PIFACE_HOME}/__init__.py"
cp "${APP_SRC}/requirements.txt" "${PIFACE_HOME}/requirements.txt"

chown -R "${PIFACE_USER}:${PIFACE_USER}" "${PIFACE_HOME}"

# ---------------------------------------------------------------------------
# 8. Python virtual environment
# ---------------------------------------------------------------------------
echo "[9/20] Creating Python virtual environment..."
python3 -m venv "${PIFACE_HOME}/venv"

echo "[10/20] Installing Python packages..."
"${PIFACE_HOME}/venv/bin/pip" install --upgrade pip setuptools wheel

"${PIFACE_HOME}/venv/bin/pip" install \
    --extra-index-url https://www.piwheels.org/simple \
    -r "${PIFACE_HOME}/requirements.txt"

# Pi-specific packages (not in requirements.txt)
"${PIFACE_HOME}/venv/bin/pip" install \
    --extra-index-url https://www.piwheels.org/simple \
    picamera2 \
    systemd-python || true  # optional, may not build on all systems

chown -R "${PIFACE_USER}:${PIFACE_USER}" "${PIFACE_HOME}/venv"

# ---------------------------------------------------------------------------
# 9. TLS certificate (self-signed, 10 years)
# ---------------------------------------------------------------------------
echo "[11/20] Generating self-signed TLS certificate..."
openssl req -x509 -nodes -newkey rsa:2048 \
    -days 3650 \
    -keyout "${PIFACE_HOME}/certs/piface.key" \
    -out    "${PIFACE_HOME}/certs/piface.crt" \
    -subj   "/CN=${WLAN_IP}/O=PiFace Attendance/C=IN" \
    -addext "subjectAltName=IP:${WLAN_IP}"

chmod 640 "${PIFACE_HOME}/certs/piface.key"
chmod 644 "${PIFACE_HOME}/certs/piface.crt"
chown "${PIFACE_USER}:${PIFACE_USER}" "${PIFACE_HOME}/certs/"*

# ---------------------------------------------------------------------------
# 10. JWT secret
# ---------------------------------------------------------------------------
echo "[12/20] Generating JWT secret..."
openssl rand -hex 32 > "${PIFACE_HOME}/config/jwt_secret.key"
chmod 400 "${PIFACE_HOME}/config/jwt_secret.key"
chown "${PIFACE_USER}:${PIFACE_USER}" "${PIFACE_HOME}/config/jwt_secret.key"

# ---------------------------------------------------------------------------
# 11. Nginx
# ---------------------------------------------------------------------------
echo "[13/20] Configuring Nginx..."
cp "${SCRIPT_DIR}/nginx.conf" /etc/nginx/sites-available/piface
ln -sf /etc/nginx/sites-available/piface /etc/nginx/sites-enabled/piface
rm -f /etc/nginx/sites-enabled/default

# Create the custom 502 error page
mkdir -p "${PIFACE_HOME}/frontend/dist"
cat > "${PIFACE_HOME}/frontend/dist/502.html" <<'HTML502'
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>PiFace - Starting</title>
<style>body{font-family:sans-serif;display:flex;justify-content:center;align-items:center;
height:100vh;margin:0;background:#1a1a2e;color:#e0e0e0;}
.box{text-align:center;padding:2rem;border:1px solid #333;border-radius:8px;background:#16213e;}
h1{color:#0f3460;}p{color:#aaa;}</style></head>
<body><div class="box"><h1>PiFace Attendance System</h1>
<p>System starting up... please wait a moment and refresh.</p></div></body></html>
HTML502
chown -R "${PIFACE_USER}:${PIFACE_USER}" "${PIFACE_HOME}/frontend"

nginx -t
systemctl enable nginx

# ---------------------------------------------------------------------------
# 12. Systemd service files
# ---------------------------------------------------------------------------
echo "[14/20] Installing systemd service files..."
cp "${SCRIPT_DIR}/piface-engine.service" /etc/systemd/system/piface-engine.service
cp "${SCRIPT_DIR}/piface-web.service"    /etc/systemd/system/piface-web.service
cp "${SCRIPT_DIR}/piface-leds.service"   /etc/systemd/system/piface-leds.service
chmod 644 /etc/systemd/system/piface-*.service
systemctl daemon-reload

# ---------------------------------------------------------------------------
# 13. Firewall (iptables)
# ---------------------------------------------------------------------------
echo "[15/20] Configuring iptables firewall..."
# Flush existing
iptables -F
iptables -X

# Load our ruleset
iptables-restore < "${SCRIPT_DIR}/iptables.rules"

# Persist
mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4

# ---------------------------------------------------------------------------
# 14. Logrotate
# ---------------------------------------------------------------------------
echo "[16/20] Installing logrotate config..."
cp "${SCRIPT_DIR}/logrotate.conf" /etc/logrotate.d/piface
chmod 644 /etc/logrotate.d/piface

# ---------------------------------------------------------------------------
# 15. Hardware & boot config
# ---------------------------------------------------------------------------
echo "[17/20] Configuring hardware and boot settings..."
BOOT_CONFIG="/boot/firmware/config.txt"

# DS3231 RTC overlay
if ! grep -q "dtoverlay=i2c-rtc,ds3231" "$BOOT_CONFIG" 2>/dev/null; then
    echo "dtoverlay=i2c-rtc,ds3231" >> "$BOOT_CONFIG"
fi

# USB max current
if ! grep -q "usb_max_current_enable=1" "$BOOT_CONFIG" 2>/dev/null; then
    echo "usb_max_current_enable=1" >> "$BOOT_CONFIG"
fi

# CPU governor to performance
echo "performance" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 2>/dev/null || true
# Make persistent via udev rule
cat > /etc/udev/rules.d/99-cpu-governor.rules <<'GOV_EOF'
SUBSYSTEM=="cpu", ACTION=="add", ATTR{cpufreq/scaling_governor}="performance"
GOV_EOF

# Timezone
timedatectl set-timezone Asia/Kolkata

# Boot to CLI
systemctl set-default multi-user.target

# Disable unnecessary services
systemctl disable bluetooth 2>/dev/null || true
systemctl disable hciuart 2>/dev/null || true
systemctl disable triggerhappy 2>/dev/null || true
systemctl mask ModemManager 2>/dev/null || true

# ---------------------------------------------------------------------------
# 16. Enable PiFace services
# ---------------------------------------------------------------------------
echo "[18/20] Enabling PiFace services..."
systemctl enable piface-leds.service
systemctl enable piface-engine.service
systemctl enable piface-web.service

# ---------------------------------------------------------------------------
# 17. Filesystem optimisation: noatime on root
# ---------------------------------------------------------------------------
echo "[19/20] Adding noatime to root filesystem..."
if ! grep -q "noatime" /etc/fstab; then
    sed -i '/[[:space:]]\/[[:space:]]/ s/defaults/defaults,noatime/' /etc/fstab
fi

# ---------------------------------------------------------------------------
# 18. Restart helper & sudoers
# ---------------------------------------------------------------------------
echo "[20/20] Installing restart helper and sudoers entry..."
cat > "${PIFACE_HOME}/helpers/restart_service.sh" <<'HELPER_EOF'
#!/bin/bash
# restart_service.sh - Restricted service restart helper for piface user.
# Only allows restarting known PiFace services.
set -euo pipefail

ALLOWED_SERVICES=("piface-engine" "piface-leds" "piface-web")

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <service-name>"
    exit 1
fi

SERVICE="$1"

for allowed in "${ALLOWED_SERVICES[@]}"; do
    if [[ "$SERVICE" == "$allowed" ]]; then
        exec systemctl restart "${SERVICE}.service"
    fi
done

echo "ERROR: Service '${SERVICE}' is not allowed. Permitted: ${ALLOWED_SERVICES[*]}"
exit 1
HELPER_EOF

chmod 755 "${PIFACE_HOME}/helpers/restart_service.sh"
chown root:root "${PIFACE_HOME}/helpers/restart_service.sh"

# Sudoers entry (drop-in file, safer than editing /etc/sudoers directly)
cat > /etc/sudoers.d/piface <<'SUDO_EOF'
# Allow piface user to restart PiFace services via the helper script
piface ALL=(root) NOPASSWD: /opt/piface/helpers/restart_service.sh
SUDO_EOF
chmod 440 /etc/sudoers.d/piface

# ---------------------------------------------------------------------------
# Final ownership pass
# ---------------------------------------------------------------------------
chown -R "${PIFACE_USER}:${PIFACE_USER}" "${PIFACE_HOME}"
# Helper must stay owned by root
chown root:root "${PIFACE_HOME}/helpers/restart_service.sh"

# ==========================================================================
echo ""
echo "=========================================="
echo " PiFace Attendance System - Install Complete"
echo "=========================================="
echo ""
echo " AP SSID  : AttendanceSystem"
echo " AP Pass  : ChangeMe123  (change in /etc/hostapd/hostapd.conf)"
echo " Web UI   : https://${WLAN_IP}"
echo " Log file : ${LOG_FILE}"
echo ""
echo " IMPORTANT: Change the default Wi-Fi password before deploying!"
echo ""
read -rp " Reboot now to apply all changes? [y/N] " answer
if [[ "${answer,,}" == "y" ]]; then
    echo "Rebooting..."
    reboot
else
    echo "Please reboot manually when ready:  sudo reboot"
fi
